language: ruby
rvm:
- 2.2.7
env:
- DB=pgsql
services:
- postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- psql -c 'create database pivotal_board_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  app: pivotal-board
  api_key:
    secure: MxnXLw2vQ9HkIPwwpzgwB+rBitFQgSNNeVvK13V8psNQ0gf+3M1JXvNcbnZEgY8HI2mkq/vrsyoAKzxB82iAPHqrrsESXktWHy+fGyFwpB1ImAKTs8IML8aw6KWnYyU6W8ah0W9nX+intSTAOjHjVR76TW6eFpmLS0lB+rcy1NbLiNcuesRy/wbm05v2C1lSIJFjDTbf+7osNnUmPuO0M7da0j43vscAtM4EZDCpJchfgSYwH9DMk902uOX1W85sifJ8tYkOPeCOe7wWjIL2ceL5lOCtSnwPundjMQyElJQ4KHCBD64FBqX/n6Kus+WEXklBgWgYL4HNnLzQaWrPiIGoz1AXoOLBJkd3FfNaSGeZ3UIpUMXz+mgrV09Deur6uh0L8XlXe8S1z1kbwK5eAux+kSib9H4376/Ab/+Fy0WhBGZQwpOEHCDvJjNC39lOgcDe0kG8WNw+/lkX1j6rw6RWqsnFCw1ra6aoIMHnxdD6W/cM55Wyb9v7WpBCfbHsar1GVK6+DA+WLXaTRGibamGbWmHmfNKSURukCoZ9nN+0ZpDKS6mdzrUrGVYqa74HQME0Iq1OOKkssN7cVeWXQ9S605hsImjhjLCE6JW71SRwsUBGgLmGHACMhrxrgRpAQqwgwWb8BfG6BjUjSt++a0GvTwtozNQikDjrFnit95A=
