development:
  adapter: postgresql
  encoding: unicode
  database: pivotal_board_dev
  pool: 5
  username: postgresql
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pivotal_board_test
  pool: 5
  username: postgresql
  password:
  host: localhost